name: Untref tests

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
            - pirulito

jobs:
    selenium-tests:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
        
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
               python-version: '3.x'
            
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install selenium
                pip install python-dotenv
                pip install requests
                pip install html-testRunner
                pip install unittest-xml-reporting

            - name: Set environment variables
              run: echo "WEB_DATA=${{ secrets.WEB_DATA}}" >> $GITHUB_ENV

            - name: Run Selenium tests
              run: |
                python -m unittest discover -s pruebas_saucelab/tests